package moodleclient.entity;
// Generated 17 juin 2022 05:48:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AssignmentSubmission generated by hbm2java
 */
public class AssignmentSubmission  implements java.io.Serializable {


     private Integer id;
     private Devoirs devoirs;
     private String fileName;
     private String hashName;
     private Date createdAt;
     private Date updatedAt;
     private Byte synced;
     private String fullName;
     private String email;
     private Double grade;

    public AssignmentSubmission() {
    }

	
    public AssignmentSubmission(String fileName) {
        this.fileName = fileName;
    }
    public AssignmentSubmission(Devoirs devoirs, String fileName, String hashName, Date createdAt, Date updatedAt, Byte synced) {
       this.devoirs = devoirs;
       this.fileName = fileName;
       this.hashName = hashName;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.synced = synced;
    }
    
    public AssignmentSubmission(Devoirs devoirs, String fileName, String hashName, Date createdAt, Date updatedAt, Byte synced, String fullName, String email, Double grade) {
       this.devoirs = devoirs;
       this.fileName = fileName;
       this.hashName = hashName;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.synced = synced;
       this.fullName = fullName;
       this.email = email;
       this.grade = grade;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Devoirs getDevoirs() {
        return this.devoirs;
    }
    
    public void setDevoirs(Devoirs devoirs) {
        this.devoirs = devoirs;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public String getHashName() {
        return this.hashName;
    }
    
    public void setHashName(String hashName) {
        this.hashName = hashName;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Byte getSynced() {
        return this.synced;
    }
    
    public void setSynced(Byte synced) {
        this.synced = synced;
    }

    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    public Double getGrade() {
        return this.grade;
    }
    
    public void setGrade(Double grade) {
        this.grade = grade;
    }


}


