package moodleclient.entity;
// Generated 17 juin 2022 05:48:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String token;
     private Date createdAt;
     private Date updatedAt;
     private String serverUrl;
     private Byte isSudent;
     private Integer remoteId;

    public Users() {
    }

	
    public Users(Date createdAt, Date updatedAt) {
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Users(String username, String password, String token, Date createdAt, Date updatedAt, String serverUrl, Byte isSudent, Integer remoteId) {
       this.username = username;
       this.password = password;
       this.token = token;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.serverUrl = serverUrl;
       this.isSudent = isSudent;
       this.remoteId = remoteId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public String getServerUrl() {
        return this.serverUrl;
    }
    
    public void setServerUrl(String serverUrl) {
        this.serverUrl = serverUrl;
    }
    public Byte getIsSudent() {
        return this.isSudent;
    }
    
    public void setIsSudent(Byte isSudent) {
        this.isSudent = isSudent;
    }
    public Integer getRemoteId() {
        return this.remoteId;
    }
    
    public void setRemoteId(Integer remoteId) {
        this.remoteId = remoteId;
    }




}


